ARG GO_VERSION

FROM --platform=$BUILDPLATFORM localhost:5000/library/golang:$GO_VERSION AS builder
ARG LDFLAGS
ARG TARGETOS
ARG TARGETARCH

WORKDIR /ec
COPY . .
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -v -o ecnet-controller -ldflags "$LDFLAGS" ./cmd/ecnet/ecnet-controller

FROM localhost:5000/distroless/static
COPY --from=builder /ec/ecnet-controller /